version: '3.8'

services:
  zabbix-eda-rulebook:
    image: zabbix-eda-rulebook
    ports:
      - "5001:5001" # Přesměrování portu
    container_name: zabbix-eda-rulebook
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    command: >
      ansible-rulebook
      --rulebook extensions/eda/rulebooks/zabbix-apache.yml
      -i inventory/inventory.yaml
      --verbose
