- name: Zabbix test rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Run playbook for office in Prague
      condition: >-
        event.payload.host_groups is select("==","Web servers") and
        event.payload.host_groups is select("==","Prague") and
        event.payload.event_tags.component is select("==","configuration")
      action:
        run_playbook:
          name: deploy-apache-prague.yaml
          inventory: inventory.yaml
...