---
- name: Troubleshoot Apache Web Server
  hosts: debian-server
  tasks:
    - name: Check Apache service status
      ansible.builtin.service_facts:
    
    - name: Restart Apache if not running
      ansible.builtin.service:
        name: apache2
        state: restarted
      when: ansible_facts.services['apache2'].state != 'running'
      become: yes
    
    - name: Notify about Apache status
      ansible.builtin.debug:
        msg: "Apache server status: {{ ansible_facts.services['apache2'].state }}"
